// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHs4vK7ArDw86SkwrPwL3Mc9PlNUJVqnk',
    appId: '1:225436362926:web:22453089bf3583746c653f',
    messagingSenderId: '225436362926',
    projectId: 'no-d42ca',
    authDomain: 'no-d42ca.firebaseapp.com',
    storageBucket: 'no-d42ca.firebasestorage.app',
    measurementId: 'G-6LVSND9QTG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrU5OmI2DDe_iTVu13Ax6xG30SWyeHfp8',
    appId: '1:225436362926:android:4a02cfad0a7eac176c653f',
    messagingSenderId: '225436362926',
    projectId: 'no-d42ca',
    storageBucket: 'no-d42ca.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtSKEFHojR9THjGtfbEVS9-KqZK6e4vDY',
    appId: '1:225436362926:ios:fcdeed65d948c2306c653f',
    messagingSenderId: '225436362926',
    projectId: 'no-d42ca',
    storageBucket: 'no-d42ca.firebasestorage.app',
    iosBundleId: 'com.capstone.capstone2Test',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAtSKEFHojR9THjGtfbEVS9-KqZK6e4vDY',
    appId: '1:225436362926:ios:fcdeed65d948c2306c653f',
    messagingSenderId: '225436362926',
    projectId: 'no-d42ca',
    storageBucket: 'no-d42ca.firebasestorage.app',
    iosBundleId: 'com.capstone.capstone2Test',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCHs4vK7ArDw86SkwrPwL3Mc9PlNUJVqnk',
    appId: '1:225436362926:web:831a94dbce0ffd6e6c653f',
    messagingSenderId: '225436362926',
    projectId: 'no-d42ca',
    authDomain: 'no-d42ca.firebaseapp.com',
    storageBucket: 'no-d42ca.firebasestorage.app',
    measurementId: 'G-JJWSGHV2WF',
  );
}
